<?php
include 'conf/db_connect.php';

// Sample data — paste your full campusStudents JSON here
$campusStudents = [
    'sosha' => [
        ['id' => '221314727', 'name' => 'Nzuzo Khanyile', 'email' => 'nkhanyile@tut4life.ac.za', 'programme' => 'Informatics', 'role' => 'Scrum Master / Business Analyst', 'specialization' => 'Project Management & Business Analysis', 'project' => 'Project 1: DOCSECURE', 'avatar' => '👨‍💼', 'categories' => ['scrum_master', 'business_analyst', 'overall', 'supportive', 'punctual']],
        ['id' => '220319849', 'name' => 'Precious Hlahla', 'email' => 'phlahla@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'Tester', 'specialization' => 'Quality Assurance', 'project' => 'Project 1: DOCSECURE', 'avatar' => '👩‍💻', 'categories' => ['tester', 'overall', 'supportive', 'punctual']],
        ['id' => '220366510', 'name' => 'Siphokuhle Komeni', 'email' => 'skomeni@tut4life.ac.za', 'programme' => 'Computer Science', 'role' => 'Front-End Developer', 'specialization' => 'UI Development', 'project' => 'Project 1: DOCSECURE', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '224555741', 'name' => 'Boitumelo Molekoa', 'email' => 'bmolekoa@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'Front-End / UI/UX Designer', 'specialization' => 'UI/UX Design', 'project' => 'Project 1: DOCSECURE', 'avatar' => '👩‍🎨', 'categories' => ['developer', 'overall', 'supportive', 'punctual']],
        [ 'id' => '220796167', 'name' => 'Hluleko Hobyani', 'email' => 'hhobyani@tut4life.ac.za', 'programme' => 'Data Science', 'role' => 'Back-End Developer', 'specialization' => 'Server Development', 'project' => 'Project 1: DOCSECURE', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],
        [ 'id' => '222507723', 'name' => 'Junior Selatlha', 'email' => 'jselatlha@tut4life.ac.za', 'programme' => 'Informatics', 'role' => 'Full-Stack Developer', 'specialization' => 'Full-Stack Development', 'project' => 'Project 1: DOCSECURE', 'avatar' => '👨‍💻', 'categories' => ['full_stack', 'developer', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '224375476', 'name' => 'Koketso Boya', 'email' => 'kboya@tut4life.ac.za', 'programme' => 'IT Management', 'role' => 'Business Analyst & System Architect', 'specialization' => 'Business Analysis & System Architecture', 'project' => 'Project 1: DOCSECURE', 'avatar' => '👨‍💼', 'categories' => ['business_analyst', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '221899229', 'name' => 'Vuthlare Rikhotso', 'email' => 'vrikhotso@tut4life.ac.za', 'programme' => 'Computer Science', 'role' => 'Back-End Developer', 'specialization' => 'Server Development', 'project' => 'Project 1: DOCSECURE', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],
        // project 2
        [ 'id' => '220768600', 'name' => 'Yamkela Zele', 'email' => 'yzele@tut4life.ac.za', 'programme' => 'IT Management', 'role' => 'Scrum Master', 'specialization' => 'Project Management', 'project' => 'Project 2: TUT GUIDE APP', 'avatar' => '👩‍💼', 'categories' => ['scrum_master', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '221272420', 'name' => 'Nonjabulo Guma', 'email' => 'nguma@tut4life.ac.za', 'programme' => 'Business Informatics', 'role' => 'BA / Tester', 'specialization' => 'Business Analysis & Testing', 'project' => 'Project 2: TUT GUIDE APP', 'avatar' => '👩‍💼', 'categories' => ['business_analyst', 'tester', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '220778169', 'name' => 'Innocent Mabasa', 'email' => 'imabasa@tut4life.ac.za', 'programme' => 'Computer Science', 'role' => 'Back-End Developer', 'specialization' => 'Server Development', 'project' => 'Project 2: TUT GUIDE APP', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],
        [ 'id' => '223005012', 'name' => 'Chantelle Moeng', 'email' => 'cmoeng@tut4life.ac.za', 'programme' => 'Data Science', 'role' => 'Front-End Developer', 'specialization' => 'UI Development', 'project' => 'Project 2: TUT GUIDE APP', 'avatar' => '👩‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],
        [ 'id' => '224118090', 'name' => 'Sihle Mathole', 'email' => 'smathole@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'Full-Stack Developer', 'specialization' => 'Full-Stack Development', 'project' => 'Project 2: TUT GUIDE APP', 'avatar' => '👨‍💻', 'categories' => ['full_stack', 'developer', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '220906779', 'name' => 'Phodiso Ramushu', 'email' => 'pramushu@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'Back-End Developer', 'specialization' => 'Server Development', 'project' => 'Project 2: TUT GUIDE APP', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],
        [ 'id' => '222878624', 'name' => 'Kaizer Maphoso', 'email' => 'kmaphoso@tut4life.ac.za', 'programme' => 'Informatics', 'role' => 'Business Analyst', 'specialization' => 'Business Analysis', 'project' => 'Project 2: TUT GUIDE APP', 'avatar' => '👨‍💼', 'categories' => ['business_analyst', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '219214588', 'name' => 'Kamogelo Mokhomole', 'email' => 'kmokhomole@tut4life.ac.za', 'programme' => 'IT Management', 'role' => 'Front-End Developer', 'specialization' => 'UI Development', 'project' => 'Project 2: TUT GUIDE APP', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],
        // PROJECT 3: INTELLIGENT SERVICE DELIVERY (MunicipalityHub)
        [ 'id' => '223669883', 'name' => 'Phiwe Mzizi', 'email' => 'pmzizi@tut4life.ac.za', 'programme' => 'Computer Science', 'role' => 'Scrum Master / BA', 'specialization' => 'Project Management & Business Analysis', 'project' => 'Project 3: MunicipalityHub', 'avatar' => '👨‍💼', 'categories' => ['scrum_master', 'business_analyst', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '221223845', 'name' => 'Sifiso Jantjie', 'email' => 'sjantjie@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'System Tester', 'specialization' => 'Quality Assurance', 'project' => 'Project 3: MunicipalityHub', 'avatar' => '👨‍💻', 'categories' => ['tester', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '223438873', 'name' => 'Olerato Manye', 'email' => 'omanye@tut4life.ac.za', 'programme' => 'Informatics', 'role' => 'Front-End Developer', 'specialization' => 'UI Development', 'project' => 'Project 3: MunicipalityHub', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],
        [ 'id' => '221286626', 'name' => 'Leago Shalang', 'email' => 'lshalang@tut4life.ac.za', 'programme' => 'Data Science', 'role' => 'Back-End Developer', 'specialization' => 'Server Development', 'project' => 'Project 3: MunicipalityHub', 'avatar' => '👩‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],
        [ 'id' => '222417961', 'name' => 'Della Raolane', 'email' => 'draolane@tut4life.ac.za', 'programme' => 'IT Management', 'role' => 'Full-Stack Developer', 'specialization' => 'Full-Stack Development', 'project' => 'Project 3: MunicipalityHub', 'avatar' => '👩‍💻', 'categories' => ['full_stack', 'developer', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '220571556', 'name' => 'Khomotjo Modiba', 'email' => 'kmodiba@tut4life.ac.za', 'programme' => 'Computer Science', 'role' => 'UX/UI Designer', 'specialization' => 'User Experience Design', 'project' => 'Project 3: MunicipalityHub', 'avatar' => '👩‍🎨', 'categories' => ['developer', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '221595491', 'name' => 'Dimpho Tukane', 'email' => 'dtukane@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'Back-End Developer', 'specialization' => 'Server Development', 'project' => 'Project 3: MunicipalityHub', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],

        // PROJECT 4: FUEL MANAGEMENT SYSTEM (LiquiTech)
        [ 'id' => '222691133', 'name' => 'Kulani Shaun Mabasa', 'email' => 'kmabasa@tut4life.ac.za', 'programme' => 'Informatics', 'role' => 'Full-Stack Developer', 'specialization' => 'Full-Stack Development', 'project' => 'Project 4: LiquiTech', 'avatar' => '👨‍💻', 'categories' => ['full_stack', 'developer', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '220492311', 'name' => 'Mkhuleko Shongwe', 'email' => 'mshongwe@tut4life.ac.za', 'programme' => 'IT Management', 'role' => 'Back-End Developer', 'specialization' => 'Server Development', 'project' => 'Project 4: LiquiTech', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],
        [ 'id' => '222661048', 'name' => 'Kamogelo Taylor Mmekwa', 'email' => 'kmmekwa@tut4life.ac.za', 'programme' => 'Computer Science', 'role' => 'Front-End Developer', 'specialization' => 'UI Development', 'project' => 'Project 4: LiquiTech', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],
        [ 'id' => '224113951', 'name' => 'Neo Terrence Mkhabela', 'email' => 'nmkhabela@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'Scrum Master', 'specialization' => 'Project Management', 'project' => 'Project 4: LiquiTech', 'avatar' => '👨‍💼', 'categories' => ['scrum_master', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '220670031', 'name' => 'Melusi Hopewell Mathebula', 'email' => 'mmathebula@tut4life.ac.za', 'programme' => 'Data Science', 'role' => 'Tester', 'specialization' => 'Quality Assurance', 'project' => 'Project 4: LiquiTech', 'avatar' => '👨‍💻', 'categories' => ['tester', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '221716213', 'name' => 'Bothale Mpatlanyane', 'email' => 'bmpatlanyane@tut4life.ac.za', 'programme' => 'Informatics', 'role' => 'Back-End Developer', 'specialization' => 'Server Development', 'project' => 'Project 4: LiquiTech', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],

        // PROJECT 5: DIGIFIKILE (EduBridge)
        [ 'id' => '223062938', 'name' => 'Lethabo Tlala', 'email' => 'ltlala@tut4life.ac.za', 'programme' => 'Data Science', 'role' => 'Scrum Master', 'specialization' => 'Project Management', 'project' => 'Project 5: EduBridge', 'avatar' => '👩‍💼', 'categories' => ['scrum_master', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '220288307', 'name' => 'Mandlenkosi Nyathi', 'email' => 'mnyathi@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'Tester', 'specialization' => 'Quality Assurance', 'project' => 'Project 5: EduBridge', 'avatar' => '👨‍💻', 'categories' => ['tester', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '220844617', 'name' => 'Inamfumu Ketsia Mwanza', 'email' => 'imwanza@tut4life.ac.za', 'programme' => 'Business Informatics', 'role' => 'Business Analyst', 'specialization' => 'Business Analysis', 'project' => 'Project 5: EduBridge', 'avatar' => '👩‍💼', 'categories' => ['business_analyst', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '220808750', 'name' => 'Siphelele Miya', 'email' => 'smiya@tut4life.ac.za', 'programme' => 'IT Management', 'role' => 'Full-Stack Developer', 'specialization' => 'Full-Stack Development', 'project' => 'Project 5: EduBridge', 'avatar' => '👨‍💻', 'categories' => ['full_stack', 'developer', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '216668731', 'name' => 'Kearabetswe Maroleni', 'email' => 'kmaroleni@tut4life.ac.za', 'programme' => 'Computer Science', 'role' => 'Front-End Developer', 'specialization' => 'UI Development', 'project' => 'Project 5: EduBridge', 'avatar' => '👩‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],
        [ 'id' => '219999470', 'name' => 'Xolane Shabalala', 'email' => 'xshabalala@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'Front-End Developer', 'specialization' => 'UI Development', 'project' => 'Project 5: EduBridge', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],
        [ 'id' => '219982623', 'name' => 'Lucky Madigoe', 'email' => 'lmadigoe@tut4life.ac.za', 'programme' => 'Computer Science', 'role' => 'Back-End Developer', 'specialization' => 'Server Development', 'project' => 'Project 5: EduBridge', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],
        [ 'id' => '218259235', 'name' => 'Siphiweyinkosi Zulu', 'email' => 'szulu@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'Back-End Developer', 'specialization' => 'Server Development', 'project' => 'Project 5: EduBridge', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],

        // PROJECT 6: SPORTS PERFORMANCE APP
        [ 'id' => '221180305', 'name' => 'Ntombi Manonga', 'email' => 'nmanonga@tut4life.ac.za', 'programme' => 'Informatics', 'role' => 'Front-End Developer', 'specialization' => 'UI Development', 'project' => 'Project 6: Sports Performance App', 'avatar' => '👩‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],
        [ 'id' => '220511286', 'name' => 'Matome Maake', 'email' => 'mmaake@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'Tester', 'specialization' => 'Quality Assurance', 'project' => 'Project 6: Sports Performance App', 'avatar' => '👨‍💻', 'categories' => ['tester', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '222949181', 'name' => 'Katlego Sebola', 'email' => 'ksebola@tut4life.ac.za', 'programme' => 'Business Informatics', 'role' => 'Business Analyst', 'specialization' => 'Business Analysis', 'project' => 'Project 6: Sports Performance App', 'avatar' => '👨‍💼', 'categories' => ['business_analyst', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '221436040', 'name' => 'Brace Mathabela', 'email' => 'bmathabela@tut4life.ac.za', 'programme' => 'IT Management', 'role' => 'DevOps', 'specialization' => 'DevOps Engineering', 'project' => 'Project 6: Sports Performance App', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '220268004', 'name' => 'Tokollo Setetemela', 'email' => 'tsetetemela@tut4life.ac.za', 'programme' => 'Computer Science', 'role' => 'UX/UI Designer', 'specialization' => 'User Experience Design', 'project' => 'Project 6: Sports Performance App', 'avatar' => '👨‍🎨', 'categories' => ['developer', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '221455827', 'name' => 'Thabiso Bokaba', 'email' => 'tbokaba@tut4life.ac.za', 'programme' => 'Data Science', 'role' => 'Data Scientist (AI/ML)', 'specialization' => 'AI/ML Development', 'project' => 'Project 6: Sports Performance App', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual'] ],
        [ 'id' => '216740092', 'name' => 'Jabulile Mhlanga', 'email' => 'jmhlanga@tut4life.ac.za', 'programme' => 'Informatics', 'role' => 'Front-End Developer', 'specialization' => 'UI Development', 'project' => 'Project 6: Sports Performance App', 'avatar' => '👩‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ],
        [ 'id' => '219569009', 'name' => 'Tiyiselani Mlangeni', 'email' => 'tmlangeni@tut4life.ac.za', 'programme' => 'Data Science', 'role' => 'Back-End Developer', 'specialization' => 'Server Development', 'project' => 'Project 6: Sports Performance App', 'avatar' => '👩‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack'] ]
    ],
    'polokwane' => [
        ['id' => '224789840', 'name' => 'Asisipho Mjojeli', 'email' => 'amjojeli@tut4life.ac.za', 'programme' => 'Computer Science', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'Project: e-LibraryLog', 'avatar' => '👩‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack', 'scrum_master']],
        ['id' => '222717841', 'name' => 'Ronewa Nthabeni', 'email' => 'rnthabeni@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'Project: e-LibraryLog', 'avatar' => '👩‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '223110568', 'name' => 'Khensani Khoza', 'email' => 'kkhoza@tut4life.ac.za', 'programme' => 'Data Science', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'Project: e-LibraryLog', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '223895956', 'name' => 'Kamogelo Thlong', 'email' => 'kthlong@tut4life.ac.za', 'programme' => 'Informatics', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'Project: e-LibraryLog', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '222958431', 'name' => 'Samukelo Khumalo', 'email' => 'skhumalo@tut4life.ac.za', 'programme' => 'IT Management', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'Project: e-LibraryLog', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '221402740', 'name' => 'Tshepo Mtungwa', 'email' => 'tmtungwa@tut4life.ac.za', 'programme' => 'Computer Science', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'Project: e-LibraryLog', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '230403716', 'name' => 'Lesego Molalatladi', 'email' => 'lmolalatladi@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'Project: e-LibraryLog', 'avatar' => '👩‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '224911670', 'name' => 'Asimbonge Msizi', 'email' => 'amsizi@tut4life.ac.za', 'programme' => 'Data Science', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'Project: e-LibraryLog', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '231933271', 'name' => 'Madimetja Kgobe', 'email' => 'mkgobe@tut4life.ac.za', 'programme' => 'Informatics', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'Project: e-LibraryLog', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '230547874', 'name' => 'Mpho Ramaloko', 'email' => 'mramaloko@tut4life.ac.za', 'programme' => 'IT Management', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'Project: e-LibraryLog', 'avatar' => '👩‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '223950116', 'name' => 'Nokwanda Hlatshwayo', 'email' => 'nhlatshwayo@tut4life.ac.za', 'programme' => 'Computer Science', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'Project: e-LibraryLog', 'avatar' => '👩‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '2320850097', 'name' => 'Thabiso Mapoulo', 'email' => 'tmapoulo@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'Project: e-LibraryLog', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']]
    ],
    'emalahleni' => [
        ['id' => '221506138', 'name' => 'Nkgasha Matlou', 'email' => 'nmatlou@tut4life.ac.za', 'programme' => 'Computer Science', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'CampusTime', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack', 'scrum_master']],
        ['id' => '223296386', 'name' => 'Ndivho Ramatshimbila', 'email' => 'nramatshimbila@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'CampusTime', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '230874123', 'name' => 'Musawekosi Manzini', 'email' => 'mmanzini@tut4life.ac.za', 'programme' => 'Data Science', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'CampusTime', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '223914926', 'name' => 'Shauntel Mtshweni', 'email' => 'smtshweni@tut4life.ac.za', 'programme' => 'Informatics', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'CampusTime', 'avatar' => '👩‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '222383714', 'name' => 'Lindokuhle Zulu', 'email' => 'lzulu@tut4life.ac.za', 'programme' => 'IT Management', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'CampusTime', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '224001258', 'name' => 'Kgethego Mabilo', 'email' => 'kmabilo@tut4life.ac.za', 'programme' => 'Computer Science', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'CampusTime', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '221619188', 'name' => 'Kgomotso Ngomane', 'email' => 'kngomane@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'CampusTime', 'avatar' => '👩‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '224251971', 'name' => 'Adel Baloyi', 'email' => 'abaloyi@tut4life.ac.za', 'programme' => 'Data Science', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'CampusTime', 'avatar' => '👩‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '224631197', 'name' => 'Amogelang Thomson', 'email' => 'athomson@tut4life.ac.za', 'programme' => 'Informatics', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'CampusTime', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '224529856', 'name' => 'Bokang Malebo', 'email' => 'bmalebo@tut4life.ac.za', 'programme' => 'IT Management', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'CampusTime', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '223959806', 'name' => 'Lindani Mayisela', 'email' => 'lmayisela@tut4life.ac.za', 'programme' => 'Computer Science', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'CampusTime', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '222864003', 'name' => 'Nomcebo Kubheka', 'email' => 'nkubheka@tut4life.ac.za', 'programme' => 'Software Engineering', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'CampusTime', 'avatar' => '👩‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '223794068', 'name' => 'Keabetswe Anta', 'email' => 'kanta@tut4life.ac.za', 'programme' => 'Data Science', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'CampusTime', 'avatar' => '👩‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '223495028', 'name' => 'Mashudu Nemutudi', 'email' => 'mnemutudi@tut4life.ac.za', 'programme' => 'Informatics', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'CampusTime', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']],
        ['id' => '230850097', 'name' => 'Mapoulo Manuel', 'email' => 'mmanuel@tut4life.ac.za', 'programme' => 'IT Management', 'role' => 'Developer', 'specialization' => 'Software Development', 'project' => 'CampusTime', 'avatar' => '👨‍💻', 'categories' => ['developer', 'overall', 'supportive', 'punctual', 'full_stack']]
    ]
];

$stmt = $conn->prepare("INSERT INTO nominations (student_id, name, email, programme, role, specialization, project, campus, avatar, categories) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)");

foreach ($campusStudents as $campus => $students) {
    foreach ($students as $student) {
        $categories = implode(',', $student['categories']);
        $stmt->bind_param(
            "ssssssssss",
            $student['id'],
            $student['name'],
            $student['email'],
            $student['programme'],
            $student['role'],
            $student['specialization'],
            $student['project'],
            $campus,
            $student['avatar'],
            $categories
        );
        $stmt->execute();
    }
}

$stmt->close();
$conn->close();

echo "✅ All nominations successfully inserted!";
?>
